name: setup-and-runs
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install
        run: npm install
      - name: run build
        run: npm run build
      - name: start
        run: npm start
      - name: run test
        run: npm test
      - run: npm run lint
        .PHONY: build
